CREATE OR REPLACE EXTERNAL TABLE 
NIFTY_DB.EXTERNAL_TABLES.NIFTY_EXT_TABLE
WITH LOCATION = @NIFTY_DB.EXTERNAL_STAGES.NIFTY_STAGE
FILE_FORMAT = NIFTY_DB.FILE_FORMATS.STOCKS_CSV_FORMAT;

SELECT * FROM NIFTY_DB.EXTERNAL_TABLES.NIFTY_EXT_TABLE
LIMIT 10;

DESC TABLE NIFTY_DB.EXTERNAL_TABLES.NIFTY_EXT_TABLE;



