CREATE OR REPLACE FILE FORMAT NIFTY_DB.FILE_FORMATS.STOCKS_CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
NULL_IF = ('//N','NULL','NULLS')
EMPTY_FIELD_AS_NULL = TRUE
DATE_FORMAT = 'YYYY-MM-DD';
