CREATE OR REPLACE STORAGE INTEGRATION NIFTY_S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::905418298466:role/niftyfiftyrole'
STORAGE_ALLOWED_LOCATIONS = ('S3://niftyfiftys3bucket/');


ALTER STORAGE INTEGRATION NIFTY_S3_INT
SET STORAGE_ALLOWED_LOCATIONS = ('s3://niftyfiftys3bucket/NiftyStocks/');

DESCRIBE STORAGE INTEGRATION NIFTY_S3_INT;