CREATE OR REPLACE DATABASE
NIFTY_DB
COMMENT = 'THIS DB CONTAINS STOCK INFORMATION';

SHOW DATABASES;

USE DATABASE NIFTY_DB;

CREATE OR REPLACE SCHEMA FILE_FORMATS;
CREATE OR REPLACE SCHEMA EXTERNAL_STAGES;
CREATE OR REPLACE SCHEMA EXTERNAL_TABLES;